# 전처리

In [6]:
import pandas as pd
import numpy as np

data = pd.read_csv("diabetes.csv")
data.head(5)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [7]:
data.describe

<bound method NDFrame.describe of      Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6
1              1       85             66             29        0  26.6
2              8      183             64              0        0  23.3
3              1       89             66             23       94  28.1
4              0      137             40             35      168  43.1
..           ...      ...            ...            ...      ...   ...
763           10      101             76             48      180  32.9
764            2      122             70             27        0  36.8
765            5      121             72             23      112  26.2
766            1      126             60              0        0  30.1
767            1       93             70             31        0  30.4

     DiabetesPedigreeFunction  Age  Outcome
0                       0.627   50        1
1                       0.351   31        0
2                       0.672   32        1
3                       0.167   21        0
4                       2.288   33        1
..                        ...  ...      ...
763                     0.171   63        0
764                     0.340   27        0
765                     0.245   30        0
766                     0.349   47        1
767                     0.315   23        0

[768 rows x 9 columns]>

In [34]:
xdata = data.iloc[:,:-1]
ydata = data.iloc[:,-1].values

In [35]:
xdata.head(2)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31

In [36]:
xdata[xdata == 0] = np.nan

In [37]:
xdata.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
count,657.000000,763.000000,733.000000,541.000000,394.000000,757.000000,768.000000,768.000000
mean,4.494673,121.686763,72.405184,29.153420,155.548223,32.457464,0.471876,33.240885
std,3.217291,30.535641,12.382158,10.476982,118.775855,6.924988,0.331329,11.760232
min,1.000000,44.000000,24.000000,7.000000,14.000000,18.200000,0.078000,21.000000
25%,2.000000,99.000000,64.000000,22.000000,76.250000,27.500000,0.243750,24.000000
50%,4.000000,117.000000,72.000000,29.000000,125.000000,32.300000,0.372500,29.000000
75%,7.000000,141.000000,80.000000,36.000000,190.000000,36.600000,0.626250,41.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000

In [38]:
xdata = xdata.fillna(xdata.mean())

In [39]:
xdata.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,4.494673,121.686763,72.405184,29.153420,155.548223,32.457464,0.471876,33.240885
std,2.975395,30.435949,12.096346,8.790942,85.021108,6.875151,0.331329,11.760232
min,1.000000,44.000000,24.000000,7.000000,14.000000,18.200000,0.078000,21.000000
25%,2.000000,99.750000,64.000000,25.000000,121.500000,27.500000,0.243750,24.000000
50%,4.494673,117.000000,72.202592,29.153420,155.548223,32.400000,0.372500,29.000000
75%,6.000000,140.250000,80.000000,32.000000,155.548223,36.600000,0.626250,41.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000

In [40]:
xdata

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6.000000,148.0,72.0,35.00000,155.548223,33.6,0.627,50
1,1.000000,85.0,66.0,29.00000,155.548223,26.6,0.351,31
2,8.000000,183.0,64.0,29.15342,155.548223,23.3,0.672,32
3,1.000000,89.0,66.0,23.00000,94.000000,28.1,0.167,21
4,4.494673,137.0,40.0,35.00000,168.000000,43.1,2.288,33
...,...,...,...,...,...,...,...,...
763,10.000000,101.0,76.0,48.00000,180.000000,32.9,0.171,63
764,2.000000,122.0,70.0,27.00000,155.548223,36.8,0.340,27
765,5.000000,121.0,72.0,23.00000,112.000000,26.2,0.245,30
766,1.000000,126.0,60.0,29.15342,155.548223,30.1,0.349,47
767,1.000000,93.0,70.0,31.00000,155.548223,30.4,0.315,23

In [42]:
ydata

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0],
      dtype=int64)

In [43]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
xdata_ss = sc.fit_transform(xdata)

print(xdata_ss.shape, ydata.shape)

(768, 8) (768,)

In [45]:
xtrain = xdata_ss[:692, :]
xtest = xdata_ss[692:, :]
ytrain = ydata[:692]
ytest = ydata[692:]

In [46]:
print(xtrain.shape, ytrain.shape, xtest.shape, ytest.shape)

(692, 8) (692,) (76, 8) (76,)

# (1)LogicGate 클래스 활용 분류

In [47]:
import numpy as np

def sigmoid(x): # 시그모이드 함수
    return 1. / (1. + np.exp(-x))

In [48]:
def numerical_derivative(f, x):
    delta_x = 1e-4
    grad = np.zeros_like(x)
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx = it.multi_index        
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) # f(x+delta_x)
        
        x[idx] = float(tmp_val) - delta_x 
        fx2 = f(x) # f(x-delta_x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        x[idx] = tmp_val 
        it.iternext()

    return grad

In [161]:
class LogicGate:
    def __init__(self, gate_name, xdata, tdata):
        self.name = gate_name
        self.xdata = xdata.reshape(692,8) # 입력층 데이터
        self.tdata = tdata.reshape(692,1) # 정답 데이터

        self.W2 = np.random.rand(8,8) # 은닉층 가중치
        self.b2 = np.random.rand(8) # 은닉층 바이어스

        self.W3 = np.random.rand(8,2) # 은닉층
        self.b3 = np.random.rand(2) # 은닉층

        self.W4 = np.random.rand(2,1)
        self.b4 = np.random.rand(1)

        self.learning_rate = 1e-1 # 학습률

    def loss_val(self):
        delta = 1e-7
        z2 = np.dot(self.xdata, self.W2) + self.b2
        a2 = sigmoid(z2)
        z3 = np.dot(a2, self.W3) + self.b3
        a3 = sigmoid(z3)
        z4 = np.dot(a3, self.W4) + self.b4
        y = a4 = sigmoid(z4)
        return -np.mean(self.tdata*np.log(y+delta)+(1-self.tdata)*np.log((1-y)+delta))

    def train(self, epoch=10000):
        f = lambda x : self.loss_val()
        print("Initial loss value = ", self.loss_val())
        for step in range(epoch+1):
            self.W2 -= self.learning_rate * numerical_derivative(f,self.W2)
            self.b2 -= self.learning_rate * numerical_derivative(f,self.b2)
            self.W3 -= self.learning_rate * numerical_derivative(f,self.W3)
            self.b3 -= self.learning_rate * numerical_derivative(f,self.b3)
            self.W4 -= self.learning_rate * numerical_derivative(f,self.W4)
            self.b4 -= self.learning_rate * numerical_derivative(f,self.b4)
            if (step % 1000 == 0):
                print("step = ", step, "loss value = ",self.loss_val()) # 학습중 손실값 출력
    
    def predict(self, input_data):
        z2 = np.dot(input_data, self.W2) + self.b2
        a2 = sigmoid(z2)
        z3 = np.dot(a2,self.W3) + self.b3
        a3 = sigmoid(z3)
        z4 = np.dot(a3, self.W4) + self.b4
        y = a4 = sigmoid(z4)
        if y > 0.5:
            result = 1
        else:
            result = 0

        return y, result

    def accuracy_score(self, test_xdata, test_tdata):
        matched_list = [] # 정답과 일치한 내용 저장
        not_matched_list = [] # 정답과 불일치한 내용 저장
        for index in range(len(test_xdata)):
            (real_val, logical_val) = self.predict(test_xdata[index])
            if logical_val == test_tdata[index]:
                matched_list.append(index) # 정답과 일치한 내용 추가
            else:
                not_matched_list.append(index) # 정답과 일치한 내용 추가

        accuracy_val = len(matched_list) / len(test_xdata) # 정확도 계산
        return accuracy_val

In [162]:
diabetes_obj = LogicGate("diabetes_GATE", xtrain, ytrain)
diabetes_obj.train(epoch=5000)

Initial loss value =  1.0189410764544364
step =  0 loss value =  0.9786825531179316
step =  1000 loss value =  0.6030044605308712
step =  2000 loss value =  0.5008464171589687
step =  3000 loss value =  0.4709761357441057
step =  4000 loss value =  0.46339875387342255
step =  5000 loss value =  0.4579280077333964

In [163]:
for data in xtest:
    sigmoid_val, logical_val = diabetes_obj.predict(data)
    print(data, " = ", logical_val)
print('------------------')
accuracy_ret = diabetes_obj.accuracy_score(xtest, ytest)
print("Accuracy => ", accuracy_ret)

[-0.83898058 -0.0225789  -0.19896517  0.32401937 -0.71261929  0.96679546
  1.25070271 -0.87137393]  =  0
[ 0.84256378  0.24043946 -0.3644121   2.25908829 -0.35953579  0.87946779
 -0.09929033  0.83038113]  =  1
[-8.38980580e-01 -1.04177506e+00 -1.02619983e+00  8.08793628e-16
 -3.34507888e-16 -1.30372418e+00 -8.48279766e-01 -7.01198424e-01]  =  0
[ 0.84256378  0.6678443   1.45550414 -0.5866013   3.81861897 -0.29945588
 -1.03854724  0.83038113]  =  1
[-0.50267171  1.55553127  0.13192869 -1.15573922 -0.35953579 -0.37222894
 -0.61573063 -0.19067191]  =  1
[ 2.98702282e-16 -7.45879399e-01  1.17557115e-15  8.08793628e-16
 -3.34507888e-16 -1.08540499e+00 -6.61032408e-01 -9.56461683e-01]  =  0
[-0.16636284  0.17468487  1.29005721 -2.06635989 -0.00645229  0.29728326
  0.38090854 -0.44593516]  =  0
[-1.66362836e-01 -1.21210789e-01 -1.98965170e-01  8.08793628e-16
 -3.34507888e-16  1.75274457e+00  1.30506485e+00 -6.16110671e-01]  =  1
[-0.83898058  0.01029839  0.29737562 -0.24511855  0.52317296  0.50104784
  0.03359489 -0.61611067]  =  0
[ 5.06254908e-01  1.08930278e-01  4.62822555e-01  2.10191786e-01
 -3.34507888e-16 -7.06985046e-01  2.81244619e-01  1.34090765e+00]  =  0
[-1.17528945e+00  1.52265398e+00  1.29005721e+00 -1.74633816e-02
 -3.34507888e-16  3.70056326e-01  1.30808497e+00  1.59617091e+00]  =  1
[-8.38980580e-01  2.40439460e-01  1.17557115e-15  8.08793628e-16
 -3.34507888e-16  8.79467786e-01 -5.07006355e-01  6.60205626e-01]  =  0
[-0.16636284 -0.38422915  0.29737562 -1.04191164 -0.65377204 -0.59054814
 -1.06874843 -0.53102292]  =  0
[ 5.06254908e-01 -1.37054801e+00  6.28269486e-01  7.79329705e-01
 -3.34507888e-16  1.06867776e+00 -8.90561427e-01 -4.45935165e-01]  =  0
[ 1.85149039e+00 -2.19842674e-01  1.17557115e-15  8.08793628e-16
 -3.34507888e-16  0.00000000e+00 -6.36871459e-01 -2.75759658e-01]  =  0
[-0.83898058  0.17468487 -2.18432835 -0.92808405  2.11204872  0.28272865
 -0.89358155 -0.95646168]  =  0
[ 1.51518152e+00  1.39114479e+00  4.62822555e-01  8.08793628e-16
 -3.34507888e-16  4.98548373e-02 -9.78144869e-01  1.00055664e+00]  =  1
[-0.83898058 -0.94314317 -0.69530596  0.32401937  0.05239496  0.80669472
  0.61043756 -0.87137393]  =  0
[-0.50267171  1.19388102 -0.69530596 -1.83870472  2.72406012 -0.18301897
 -0.53418742 -0.78628618]  =  1
[ 0.16994604  0.14180757  0.46282255 -0.24511855 -1.57178914 -0.41589278
 -0.09929033  0.57511787]  =  0
[ 1.85149039e+00  2.40439460e-01 -8.60752896e-01  7.79329705e-01
 -3.34507888e-16  1.27244234e+00 -9.32500966e-02  4.04942367e-01]  =  1
[ 2.98702282e-16  4.04825936e-01 -1.19164676e+00 -1.04191164e+00
  1.59419291e+00 -8.81640403e-01 -3.62040659e-01 -1.04154944e+00]  =  0
[-5.02671708e-01 -6.47247513e-01  1.31928692e-01  8.08793628e-16
 -3.34507888e-16 -4.30447396e-01 -1.05968807e+00 -1.05584152e-01]  =  0
[ 0.84256378  2.14732259 -1.85343448  0.43784695  2.78290737  0.20995558
  1.06949559  0.06459135]  =  1
[-0.50267171  1.68704045  0.46282255  1.12081246  0.34663121  0.19540097
  1.50439268 -0.19067191]  =  1
[ 1.85149039e+00 -9.10265875e-01 -3.35182392e-02 -1.26956680e+00
 -3.34507888e-16 -1.36194264e+00  3.71848180e-01  1.93652192e+00]  =  0
[-1.17528945 -0.44998374 -1.02619983  1.91760554  0.26424506  0.44282939
 -0.17177318 -0.78628618]  =  0
[ 1.69946036e-01 -8.11633989e-01  2.97375623e-01 -2.45118549e-01
 -3.34507888e-16  4.57384005e-01 -2.83517573e-01  1.59617091e+00]  =  0
[-1.66362836e-01 -1.27191612e+00  1.12461028e+00 -1.15573922e+00
 -3.34507888e-16 -4.59556622e-01 -4.67744813e-01  6.45913543e-02]  =  0
[-1.17528945 -0.25271997 -0.52985903  0.7793297   0.52317296  0.82124933
 -0.55230814 -1.04154944]  =  0
[-1.17528945  0.89798537 -0.3644121  -0.01746338 -0.33599689 -0.45955662
 -0.37110101  0.74529338]  =  0
[ 0.16994604 -0.15408808  1.12461028  0.0963642  -0.59492479  0.96679546
 -0.66707265  0.74529338]  =  0
[-1.17528945e+00 -3.51351855e-01  1.78639801e+00  8.08793628e-16
 -3.34507888e-16  4.98548373e-02 -6.24790984e-01  1.00055664e+00]  =  0
[-1.66362836e-01 -3.18474560e-01  4.62822555e-01  1.23464004e+00
 -3.34507888e-16  1.01045930e+00 -7.12374425e-01  4.04942367e-01]  =  0
[-1.17528945 -0.18696538  0.46282255 -0.01746338  0.28778396  0.53015707
  0.07285643 -0.70119842]  =  0
[ 2.98702282e-16  6.34967003e-01  9.59163349e-01 -3.58946133e-01
 -3.34507888e-16 -8.36361521e-03 -1.17411046e-01 -9.56461683e-01]  =  0
[-8.38980580e-01  1.75279504e+00  1.29005721e+00  8.08793628e-16
 -3.34507888e-16 -1.39105186e+00 -4.40563745e-01 -9.56461683e-01]  =  0
[-8.38980580e-01 -9.76020466e-01 -1.68798755e+00  8.08793628e-16
 -3.34507888e-16 -3.43119717e-01 -9.99285700e-01 -9.56461683e-01]  =  0
[-0.50267171  0.27331675  0.46282255 -0.70042888 -0.90093049 -0.59054814
 -0.4496241   0.06459135]  =  0
[ 1.17887265e+00 -5.54561979e-02  1.12461028e+00  8.08793628e-16
 -3.34507888e-16 -5.90548141e-01 -6.42911696e-01 -9.56461683e-01]  =  0
[-0.83898058  1.71991775  1.29005721  0.89315729 -0.41838304  1.75274457
  0.52587423 -0.78628618]  =  1
[-0.83898058 -0.51573833 -1.35709369 -0.24511855  0.11124221 -0.50322046
 -0.13855188 -0.95646168]  =  0
[-8.38980580e-01 -5.48615627e-01  2.14652158e-01  8.08793628e-16
 -3.34507888e-16 -1.33283341e+00  2.66144026e-01  1.68125866e+00]  =  0
[-1.66362836e-01 -8.77388580e-01 -1.02619983e+00  3.24019370e-01
 -3.34507888e-16  4.28274779e-01 -5.67408729e-01 -4.45935165e-01]  =  0
[ 2.98702282e-16  1.41807574e-01  1.12461028e+00 -2.45118549e-01
 -4.18383038e-01 -7.36094272e-01  1.30238686e-01 -1.04154944e+00]  =  0
[ 1.17887265e+00 -1.86370744e+00 -3.35182392e-02 -7.00428884e-01
 -3.34507888e-16 -6.65820677e-02  3.86948773e-01  7.45293379e-01]  =  0
[-0.83898058 -0.7458794  -1.02619983 -1.38339439  0.05239496  0.60293014
 -0.05700867 -1.04154944]  =  0
[-1.17528945e+00 -6.47247513e-01  1.31928692e-01  8.08793628e-16
 -3.34507888e-16  1.02501392e+00 -5.40227661e-01  7.45293379e-01]  =  0
[ 2.18779927 -0.0554562   0.62826949  0.89315729 -0.06529954  1.43254309
  0.94567073  1.2558199 ]  =  1
[-0.50267171 -0.64724751 -2.34977528 -1.04191164 -0.72438874 -0.24123743
 -0.21707496 -0.61611067]  =  0
[-1.17528945 -0.41710645 -1.19164676 -1.2695668  -0.46546084 -0.57599353
 -0.76371644 -0.95646168]  =  0
[ 1.51518152e+00  6.02089708e-01  1.78639801e+00  8.08793628e-16
 -3.34507888e-16  3.53002242e-02  7.91644676e-01  1.00055664e+00]  =  1
[ 2.86041701  1.02949455  1.29005721  0.89315729 -0.18299404  1.18511466
  2.12049689  0.49003012]  =  1
[ 2.52410814 -0.7130021   0.95916335  0.43784695 -0.59492479 -0.35767433
  0.04869548  1.08564439]  =  0
[-1.17528945e+00  8.32230775e-01  1.78639801e+00  1.34846762e+00
 -3.34507888e-16  2.45136600e+00 -3.43919947e-01 -5.31022918e-01]  =  1
[-1.17528945 -1.33767071  0.13192869  1.34846762 -1.15985839  2.01472761
  1.88492764 -0.10558415]  =  0
[-0.50267171  2.14732259 -0.19896517 -0.81425647  0.52317296  0.57382091
 -0.19291401  0.23476686]  =  1
[ 5.06254908e-01  1.32539020e+00 -8.60752896e-01  8.08793628e-16
 -3.34507888e-16 -1.18728728e+00 -8.87541309e-01  1.42599540e+00]  =  1
[-1.66362836e-01  4.70580527e-01 -1.98965170e-01  8.08793628e-16
 -3.34507888e-16 -1.83018973e-01  2.14465784e+00 -9.56461683e-01]  =  1
[-1.17528945 -0.0225789   0.46282255  1.12081246 -0.95977774  0.95224085
 -0.63687146 -0.44593516]  =  0
[-5.02671708e-01 -4.49983741e-01 -8.60752896e-01 -5.86601300e-01
 -3.34507888e-16 -9.39858856e-01 -7.51635968e-01 -7.01198424e-01]  =  0
[ 2.98702282e-16  1.95005881e+00  1.29005721e+00  1.68995037e+00
  4.17170247e+00  1.57808922e+00 -7.54656087e-01 -6.16110671e-01]  =  1
[ 1.17887265e+00  1.06237184e+00  4.62822555e-01  3.24019370e-01
 -3.34507888e-16 -8.36361521e-03 -8.72098593e-02  1.00055664e+00]  =  1
[-1.17528945  0.20756216  1.29005721  1.12081246 -0.53607754  0.58837552
  1.76714301  0.31985461]  =  1
[ 8.42563779e-01  5.03457822e-01  1.45550414e+00  1.34846762e+00
 -3.34507888e-16 -6.65820677e-02 -2.44256030e-01  4.90030120e-01]  =  1
[ 2.98702282e-16  4.31756879e-02 -3.35182392e-02  8.08793628e-16
 -3.34507888e-16  5.59266297e-01 -6.45931815e-01  1.59617091e+00]  =  0
[-1.17528945e+00 -5.15738332e-01  2.97375623e-01  8.08793628e-16
 -3.34507888e-16  7.33921655e-01 -8.30159054e-01 -6.16110671e-01]  =  0
[ 5.06254908e-01  2.24595447e+00  1.62095107e+00  8.08793628e-16
 -3.34507888e-16  4.42829392e-01 -5.85529441e-01  2.78739945e+00]  =  1
[-0.83898058 -1.10752965 -1.19164676 -0.35894613 -1.64240584 -0.59054814
  0.88828847 -0.95646168]  =  0
[ 1.51518152e+00  1.58840857e+00  1.31928692e-01  2.10191786e-01
 -3.34507888e-16  1.67997151e+00 -2.08014606e-01  8.30381132e-01]  =  1
[ 1.51518152e+00 -1.07465235e+00 -8.60752896e-01  8.08793628e-16
 -3.34507888e-16 -1.44927032e+00 -9.96265581e-01 -2.04963989e-02]  =  0
[ 1.85149039 -0.68012481  0.29737562  2.14526071  0.28778396  0.06440945
 -0.90868214  2.5321362 ]  =  0
[-8.38980580e-01  1.02983926e-02 -1.98965170e-01 -2.45118549e-01
 -3.34507888e-16  6.32039363e-01 -3.98282083e-01 -5.31022918e-01]  =  0
[ 0.16994604 -0.0225789  -0.03351824 -0.70042888 -0.51253864 -0.91074963
 -0.68519336 -0.27575966]  =  0
[-1.17528945e+00  1.41807574e-01 -1.02619983e+00  8.08793628e-16
 -3.34507888e-16 -3.43119717e-01 -3.71101015e-01  1.17073215e+00]  =  0
[-1.17528945e+00 -9.43143171e-01 -1.98965170e-01  2.10191786e-01
 -3.34507888e-16 -2.99455878e-01 -4.73785050e-01 -8.71373930e-01]  =  0
------------------
Accuracy =>  0.8157894736842105

# (2)케라스 라이브러리 활용 분류

In [148]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Dense
from tensorflow.keras.optimizers import SGD
import numpy as np

In [149]:
model = Sequential()
model.add(Flatten(input_shape=(8,))) # 입력층
model.add(Dense(8, activation='relu')) # 은닉층
model.add(Dense(2, activation='relu')) # 은닉층
model.add(Dense(1, activation='sigmoid')) # 출력층 이진분류 : sigmoid, 다중분류: softmax
model.compile(optimizer=SGD(learning_rate=1e-2), loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential_18"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 flatten_18 (Flatten)        (None, 8)                 0

 dense_51 (Dense)            (None, 8)                 72

 dense_52 (Dense)            (None, 2)                 18

 dense_53 (Dense)            (None, 1)                 3

=================================================================
Total params: 93 (372.00 Byte)
Trainable params: 93 (372.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [150]:
hist = model.fit(xtrain, ytrain, epochs=1000, batch_size=32)

Epoch 1/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.7347 - accuracy: 0.6561
Epoch 2/1000
22/22 [==============================] - 0s 707us/step - loss: 0.7256 - accuracy: 0.6561
Epoch 3/1000
22/22 [==============================] - 0s 810us/step - loss: 0.7179 - accuracy: 0.6561
Epoch 4/1000
22/22 [==============================] - 0s 747us/step - loss: 0.7109 - accuracy: 0.6561
Epoch 5/1000
22/22 [==============================] - 0s 718us/step - loss: 0.7046 - accuracy: 0.6561
Epoch 6/1000
22/22 [==============================] - 0s 1ms/step - loss: 0.6990 - accuracy: 0.6561
Epoch 7/1000
22/22 [==============================] - 0s 1ms/step - loss: 0.6941 - accuracy: 0.6561
Epoch 8/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.6895 - accuracy: 0.6561
Epoch 9/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.6854 - accuracy: 0.6561
Epoch 10/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.6817 - accuracy: 0.6561
Epoch 11/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.6782 - accuracy: 0.6561
Epoch 12/1000
22/22 [==============================] - 0s 1ms/step - loss: 0.6752 - accuracy: 0.6561
Epoch 13/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.6722 - accuracy: 0.6561
Epoch 14/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.6694 - accuracy: 0.6561
Epoch 15/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.6666 - accuracy: 0.6561
Epoch 16/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.6639 - accuracy: 0.6561
Epoch 17/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.6614 - accuracy: 0.6561
Epoch 18/1000
22/22 [==============================] - 0s 1000us/step - loss: 0.6591 - accuracy: 0.6561
Epoch 19/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.6571 - accuracy: 0.6561
Epoch 20/1000
22/22 [==============================] - 0s 1ms/step - loss: 0.6551 - accuracy: 0.6561
Epoch 21/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.6531 - accuracy: 0.6561
Epoch 22/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.6510 - accuracy: 0.6561
Epoch 23/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.6490 - accuracy: 0.6561
Epoch 24/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.6470 - accuracy: 0.6561
Epoch 25/1000
22/22 [==============================] - 0s 1ms/step - loss: 0.6450 - accuracy: 0.6561
Epoch 26/1000
22/22 [==============================] - 0s 1ms/step - loss: 0.6427 - accuracy: 0.6561
Epoch 27/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.6400 - accuracy: 0.6561
Epoch 28/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.6370 - accuracy: 0.6561
Epoch 29/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.6340 - accuracy: 0.6561
Epoch 30/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.6310 - accuracy: 0.6561
Epoch 31/1000
22/22 [==============================] - 0s 1ms/step - loss: 0.6277 - accuracy: 0.6561
Epoch 32/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.6242 - accuracy: 0.6561
Epoch 33/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.6205 - accuracy: 0.6561
Epoch 34/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.6168 - accuracy: 0.6561
Epoch 35/1000
22/22 [==============================] - 0s 1ms/step - loss: 0.6128 - accuracy: 0.6561
Epoch 36/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.6087 - accuracy: 0.6561
Epoch 37/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.6047 - accuracy: 0.6561
Epoch 38/1000
22/22 [==============================] - 0s 952us/step - loss: 0.6007 - accuracy: 0.6561
Epoch 39/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5968 - accuracy: 0.6561
Epoch 40/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5931 - accuracy: 0.6561
Epoch 41/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5895 - accuracy: 0.6561
Epoch 42/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5860 - accuracy: 0.6561
Epoch 43/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5824 - accuracy: 0.6561
Epoch 44/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5790 - accuracy: 0.6561
Epoch 45/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5758 - accuracy: 0.6561
Epoch 46/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5730 - accuracy: 0.6561
Epoch 47/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5704 - accuracy: 0.6561
Epoch 48/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5680 - accuracy: 0.6561
Epoch 49/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5658 - accuracy: 0.6561
Epoch 50/1000
22/22 [==============================] - 0s 1ms/step - loss: 0.5638 - accuracy: 0.6561
Epoch 51/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5618 - accuracy: 0.6561
Epoch 52/1000
22/22 [==============================] - 0s 967us/step - loss: 0.5599 - accuracy: 0.6561
Epoch 53/1000
22/22 [==============================] - 0s 1ms/step - loss: 0.5582 - accuracy: 0.6561
Epoch 54/1000
22/22 [==============================] - 0s 1ms/step - loss: 0.5564 - accuracy: 0.6561
Epoch 55/1000
22/22 [==============================] - 0s 1ms/step - loss: 0.5547 - accuracy: 0.6561
Epoch 56/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5531 - accuracy: 0.6561
Epoch 57/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5515 - accuracy: 0.6561
Epoch 58/1000
22/22 [==============================] - 0s 1ms/step - loss: 0.5500 - accuracy: 0.6561
Epoch 59/1000
22/22 [==============================] - 0s 1ms/step - loss: 0.5485 - accuracy: 0.6561
Epoch 60/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5470 - accuracy: 0.6561
Epoch 61/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5457 - accuracy: 0.6561
Epoch 62/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5444 - accuracy: 0.6561
Epoch 63/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5431 - accuracy: 0.6561
Epoch 64/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5418 - accuracy: 0.6561
Epoch 65/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5405 - accuracy: 0.6561
Epoch 66/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5393 - accuracy: 0.6561
Epoch 67/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5380 - accuracy: 0.6561
Epoch 68/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5368 - accuracy: 0.6561
Epoch 69/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5358 - accuracy: 0.6561
Epoch 70/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5347 - accuracy: 0.6561
Epoch 71/1000
22/22 [==============================] - 0s 1ms/step - loss: 0.5337 - accuracy: 0.6561
Epoch 72/1000
22/22 [==============================] - 0s 1ms/step - loss: 0.5328 - accuracy: 0.6561
Epoch 73/1000
22/22 [==============================] - 0s 1ms/step - loss: 0.5317 - accuracy: 0.6561
Epoch 74/1000
22/22 [==============================] - 0s 1ms/step - loss: 0.5308 - accuracy: 0.6561
Epoch 75/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5298 - accuracy: 0.6561
Epoch 76/1000
22/22 [==============================] - 0s 1ms/step - loss: 0.5289 - accuracy: 0.6561
Epoch 77/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5280 - accuracy: 0.6561
Epoch 78/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5272 - accuracy: 0.6561
Epoch 79/1000
22/22 [==============================] - 0s 1ms/step - loss: 0.5264 - accuracy: 0.6561
Epoch 80/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5256 - accuracy: 0.6561
Epoch 81/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5248 - accuracy: 0.6561
Epoch 82/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5241 - accuracy: 0.6561
Epoch 83/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5233 - accuracy: 0.6561
Epoch 84/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5226 - accuracy: 0.6561
Epoch 85/1000
22/22 [==============================] - 0s 1ms/step - loss: 0.5219 - accuracy: 0.6561
Epoch 86/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5213 - accuracy: 0.6561
Epoch 87/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5205 - accuracy: 0.6561
Epoch 88/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5198 - accuracy: 0.6561
Epoch 89/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5190 - accuracy: 0.6561
Epoch 90/1000
22/22 [==============================] - 0s 1ms/step - loss: 0.5182 - accuracy: 0.6561
Epoch 91/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5175 - accuracy: 0.6561
Epoch 92/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5168 - accuracy: 0.6561
Epoch 93/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5159 - accuracy: 0.6561
Epoch 94/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5151 - accuracy: 0.6561
Epoch 95/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5143 - accuracy: 0.6561
Epoch 96/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5136 - accuracy: 0.6561
Epoch 97/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5128 - accuracy: 0.6835
Epoch 98/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5122 - accuracy: 0.7269
Epoch 99/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5114 - accuracy: 0.7312
Epoch 100/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5108 - accuracy: 0.7312
Epoch 101/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5101 - accuracy: 0.7327
Epoch 102/1000
22/22 [==============================] - 0s 952us/step - loss: 0.5095 - accuracy: 0.7327
Epoch 103/1000
22/22 [==============================] - 0s 1ms/step - loss: 0.5089 - accuracy: 0.7341
Epoch 104/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5084 - accuracy: 0.7312
Epoch 105/1000
22/22 [==============================] - 0s 1ms/step - loss: 0.5079 - accuracy: 0.7312
Epoch 106/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5074 - accuracy: 0.7327
Epoch 107/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5069 - accuracy: 0.7327
Epoch 108/1000
22/22 [==============================] - 0s 1ms/step - loss: 0.5064 - accuracy: 0.7327
Epoch 109/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5059 - accuracy: 0.7355
Epoch 110/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5054 - accuracy: 0.7370
Epoch 111/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5051 - accuracy: 0.7370
Epoch 112/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5046 - accuracy: 0.7370
Epoch 113/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5040 - accuracy: 0.7370
Epoch 114/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5035 - accuracy: 0.7399
Epoch 115/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5030 - accuracy: 0.7370
Epoch 116/1000
22/22 [==============================] - 0s 1ms/step - loss: 0.5025 - accuracy: 0.7370
Epoch 117/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5019 - accuracy: 0.7399
Epoch 118/1000
22/22 [==============================] - 0s 1ms/step - loss: 0.5015 - accuracy: 0.7413
Epoch 119/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5010 - accuracy: 0.7399
Epoch 120/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.5004 - accuracy: 0.7384
Epoch 121/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.4999 - accuracy: 0.7428
Epoch 122/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.4994 - accuracy: 0.7428
Epoch 123/1000
22/22 [==============================] - 0s 1ms/step - loss: 0.4988 - accuracy: 0.7428
Epoch 124/1000
22/22 [==============================] - 0s 873us/step - loss: 0.4982 - accuracy: 0.7428
Epoch 125/1000
22/22 [==============================] - 0s 637us/step - loss: 0.4976 - accuracy: 0.7457
Epoch 126/1000
22/22 [==============================] - 0s 647us/step - loss: 0.4971 - accuracy: 0.7442
Epoch 127/1000
22/22 [==============================] - 0s 646us/step - loss: 0.4965 - accuracy: 0.7442
Epoch 128/1000
22/22 [==============================] - 0s 677us/step - loss: 0.4960 - accuracy: 0.7457
Epoch 129/1000
22/22 [==============================] - 0s 647us/step - loss: 0.4955 - accuracy: 0.7442
Epoch 130/1000
22/22 [==============================] - 0s 634us/step - loss: 0.4950 - accuracy: 0.7457
Epoch 131/1000
22/22 [==============================] - 0s 736us/step - loss: 0.4946 - accuracy: 0.7500
Epoch 132/1000
22/22 [==============================] - 0s 675us/step - loss: 0.4941 - accuracy: 0.7500
Epoch 133/1000
22/22 [==============================] - 0s 681us/step - loss: 0.4936 - accuracy: 0.7529
Epoch 134/1000
22/22 [==============================] - 0s 698us/step - loss: 0.4932 - accuracy: 0.7529
Epoch 135/1000
22/22 [==============================] - 0s 746us/step - loss: 0.4928 - accuracy: 0.7543
Epoch 136/1000
22/22 [==============================] - 0s 667us/step - loss: 0.4924 - accuracy: 0.7543
Epoch 137/1000
22/22 [==============================] - 0s 709us/step - loss: 0.4919 - accuracy: 0.7529
Epoch 138/1000
22/22 [==============================] - 0s 3ms/step - loss: 0.4915 - accuracy: 0.7558
Epoch 139/1000
22/22 [==============================] - 0s 1ms/step - loss: 0.4910 - accuracy: 0.7558
Epoch 140/1000
22/22 [==============================] - 0s 1ms/step - loss: 0.4906 - accuracy: 0.7543
Epoch 141/1000
22/22 [==============================] - 0s 1ms/step - loss: 0.4901 - accuracy: 0.7543
Epoch 142/1000
22/22 [==============================] - 0s 1ms/step - loss: 0.4897 - accuracy: 0.7543
Epoch 143/1000
22/22 [==============================] - 0s 976us/step - loss: 0.4892 - accuracy: 0.7543
Epoch 144/1000
22/22 [==============================] - 0s 1ms/step - loss: 0.4887 - accuracy: 0.7529
Epoch 145/1000
22/22 [==============================] - 0s 905us/step - loss: 0.4882 - accuracy: 0.7558
Epoch 146/1000
22/22 [==============================] - 0s 714us/step - loss: 0.4878 - accuracy: 0.7514
Epoch 147/1000
22/22 [==============================] - 0s 762us/step - loss: 0.4873 - accuracy: 0.7514
Epoch 148/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.4868 - accuracy: 0.7500
Epoch 149/1000
22/22 [==============================] - 0s 1ms/step - loss: 0.4863 - accuracy: 0.7500
Epoch 150/1000
22/22 [==============================] - 0s 905us/step - loss: 0.4859 - accuracy: 0.7529
Epoch 151/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.4855 - accuracy: 0.7514
Epoch 152/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.4850 - accuracy: 0.7543
Epoch 153/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.4846 - accuracy: 0.7543
Epoch 154/1000
22/22 [==============================] - 0s 1ms/step - loss: 0.4842 - accuracy: 0.7529
Epoch 155/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.4837 - accuracy: 0.7529
Epoch 156/1000
22/22 [==============================] - 0s 1ms/step - loss: 0.4834 - accuracy: 0.7529
Epoch 157/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.4829 - accuracy: 0.7543
Epoch 158/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.4824 - accuracy: 0.7558
Epoch 159/1000
22/22 [==============================] - 0s 1ms/step - loss: 0.4820 - accuracy: 0.7572
Epoch 160/1000
22/22 [==============================] - 0s 952us/step - loss: 0.4817 - accuracy: 0.7572
Epoch 161/1000
22/22 [==============================] - 0s 857us/step - loss: 0.4814 - accuracy: 0.7630
Epoch 162/1000
22/22 [==============================] - 0s 737us/step - loss: 0.4809 - accuracy: 0.7630
Epoch 163/1000
22/22 [==============================] - 0s 798us/step - loss: 0.4806 - accuracy: 0.7645
Epoch 164/1000
22/22 [==============================] - 0s 807us/step - loss: 0.4802 - accuracy: 0.7616
Epoch 165/1000
22/22 [==============================] - 0s 746us/step - loss: 0.4800 - accuracy: 0.7659
Epoch 166/1000
22/22 [==============================] - 0s 804us/step - loss: 0.4796 - accuracy: 0.7659
Epoch 167/1000
22/22 [==============================] - 0s 791us/step - loss: 0.4793 - accuracy: 0.7630
Epoch 168/1000
22/22 [==============================] - 0s 685us/step - loss: 0.4790 - accuracy: 0.7630
Epoch 169/1000
22/22 [==============================] - 0s 684us/step - loss: 0.4787 - accuracy: 0.7630
Epoch 170/1000
22/22 [==============================] - 0s 727us/step - loss: 0.4783 - accuracy: 0.7645
Epoch 171/1000
22/22 [==============================] - 0s 733us/step - loss: 0.4781 - accuracy: 0.7659
Epoch 172/1000
22/22 [==============================] - 0s 722us/step - loss: 0.4778 - accuracy: 0.7630
Epoch 173/1000
22/22 [==============================] - 0s 737us/step - loss: 0.4775 - accuracy: 0.7630
Epoch 174/1000
22/22 [==============================] - 0s 720us/step - loss: 0.4773 - accuracy: 0.7630
Epoch 175/1000
22/22 [==============================] - 0s 735us/step - loss: 0.4770 - accuracy: 0.7616
Epoch 176/1000
22/22 [==============================] - 0s 710us/step - loss: 0.4768 - accuracy: 0.7616
Epoch 177/1000
22/22 [==============================] - 0s 721us/step - loss: 0.4765 - accuracy: 0.7601
Epoch 178/1000
22/22 [==============================] - 0s 686us/step - loss: 0.4763 - accuracy: 0.7601
Epoch 179/1000
22/22 [==============================] - 0s 781us/step - loss: 0.4761 - accuracy: 0.7601
Epoch 180/1000
22/22 [==============================] - 0s 740us/step - loss: 0.4759 - accuracy: 0.7601
Epoch 181/1000
22/22 [==============================] - 0s 682us/step - loss: 0.4757 - accuracy: 0.7601
Epoch 182/1000
22/22 [==============================] - 0s 667us/step - loss: 0.4754 - accuracy: 0.7601
Epoch 183/1000
22/22 [==============================] - 0s 783us/step - loss: 0.4753 - accuracy: 0.7616
Epoch 184/1000
22/22 [==============================] - 0s 797us/step - loss: 0.4750 - accuracy: 0.7616
Epoch 185/1000
22/22 [==============================] - 0s 833us/step - loss: 0.4749 - accuracy: 0.7616
Epoch 186/1000
22/22 [==============================] - 0s 751us/step - loss: 0.4746 - accuracy: 0.7616
Epoch 187/1000
22/22 [==============================] - 0s 734us/step - loss: 0.4745 - accuracy: 0.7616
Epoch 188/1000
22/22 [==============================] - 0s 752us/step - loss: 0.4744 - accuracy: 0.7616
Epoch 189/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.4742 - accuracy: 0.7645
Epoch 190/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.4741 - accuracy: 0.7630
Epoch 191/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.4738 - accuracy: 0.7630
Epoch 192/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.4738 - accuracy: 0.7630
Epoch 193/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.4736 - accuracy: 0.7645
Epoch 194/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.4735 - accuracy: 0.7616
Epoch 195/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.4732 - accuracy: 0.7645
Epoch 196/1000
22/22 [==============================] - 0s 2ms/step - loss: 0.4732 - accuracy: 0.7645

In [151]:
pred = model.predict(xtest)
pred

3/3 [==============================] - 0s 2ms/step

array([[0.62757444],
       [0.6714383 ],
       [0.01358446],
       [0.02936485],
       [0.6072625 ],
       [0.00643807],
       [0.04655016],
       [0.74930525],
       [0.14936836],
       [0.5193682 ],
       [0.74930525],
       [0.5740595 ],
       [0.12373693],
       [0.10873196],
       [0.74930525],
       [0.47712803],
       [0.74600667],
       [0.11914463],
       [0.05198159],
       [0.24121507],
       [0.74930525],
       [0.05588094],
       [0.14756161],
       [0.74930525],
       [0.74930525],
       [0.1292317 ],
       [0.09118009],
       [0.23419279],
       [0.00540671],
       [0.12756406],
       [0.39605546],
       [0.4795652 ],
       [0.39229056],
       [0.5424616 ],
       [0.07294268],
       [0.0767363 ],
       [0.02643979],
       [0.02102902],
       [0.45770943],
       [0.02491919],
       [0.74930525],
       [0.03861053],
       [0.38153315],
       [0.13018209],
       [0.00834072],
       [0.07605311],
       [0.09704008],
       [0.5118655 ],
       [0.74930525],
       [0.07596234],
       [0.04057021],
       [0.74930525],
       [0.74930525],
       [0.19419909],
       [0.74930525],
       [0.38458103],
       [0.74930525],
       [0.6125068 ],
       [0.7448568 ],
       [0.19218943],
       [0.07014427],
       [0.5475922 ],
       [0.74930525],
       [0.74930525],
       [0.74930525],
       [0.3841    ],
       [0.14113405],
       [0.41055575],
       [0.01122175],
       [0.74930525],
       [0.07084611],
       [0.03854252],
       [0.33648467],
       [0.307184  ],
       [0.32451284],
       [0.01371843]], dtype=float32)

In [152]:
model.evaluate(xtest, ytest)

3/3 [==============================] - 0s 3ms/step - loss: 0.4781 - accuracy: 0.8026

[0.4780704975128174, 0.8026315569877625]