In [1]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
import np_utils # pip install np_utils
from keras.utils import to_categorical
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

WARNING:tensorflow:From C:\Project\Python_Source\AI01\.venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [2]:
df = pd.read_csv("./titanic/train.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [3]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [4]:
df = df.fillna(df.mode().iloc[0])
data = df.drop(columns=['Cabin','PassengerId','Name','SibSp','Parch','Ticket','Embarked'])
data

     Survived  Pclass     Sex   Age     Fare
0           0       3    male  22.0   7.2500
1           1       1  female  38.0  71.2833
2           1       3  female  26.0   7.9250
3           1       1  female  35.0  53.1000
4           0       3    male  35.0   8.0500
..        ...     ...     ...   ...      ...
886         0       2    male  27.0  13.0000
887         1       1  female  19.0  30.0000
888         0       3  female  24.0  23.4500
889         1       1    male  26.0  30.0000
890         0       3    male  32.0   7.7500

[891 rows x 5 columns]

In [5]:
data.isna().sum()

Survived    0
Pclass      0
Sex         0
Age         0
Fare        0
dtype: int64

In [6]:
data["Fare"] = np.log1p(data["Fare"])
data.describe()

         Survived      Pclass         Age        Fare
count  891.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   28.566970    2.962246
std      0.486592    0.836071   13.199572    0.969048
min      0.000000    1.000000    0.420000    0.000000
25%      0.000000    2.000000   22.000000    2.187218
50%      0.000000    3.000000   24.000000    2.737881
75%      1.000000    3.000000   35.000000    3.465736
max      1.000000    3.000000   80.000000    6.240917

In [7]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
data["Age"] = sc.fit_transform(df[["Age"]])
data.describe()

         Survived      Pclass           Age        Fare
count  891.000000  891.000000  8.910000e+02  891.000000
mean     0.383838    2.308642  5.980999e-17    2.962246
std      0.486592    0.836071  1.000562e+00    0.969048
min      0.000000    1.000000 -2.133613e+00    0.000000
25%      0.000000    2.000000 -4.977933e-01    2.187218
50%      0.000000    3.000000 -3.461881e-01    2.737881
75%      1.000000    3.000000  4.876403e-01    3.465736
max      1.000000    3.000000  3.898757e+00    6.240917

In [8]:
from sklearn.preprocessing import MinMaxScaler

sc = MinMaxScaler()
data["Age"] = sc.fit_transform(df[["Age"]])
data.describe()

         Survived      Pclass         Age        Fare
count  891.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642    0.353694    2.962246
std      0.486592    0.836071    0.165865    0.969048
min      0.000000    1.000000    0.000000    0.000000
25%      0.000000    2.000000    0.271174    2.187218
50%      0.000000    3.000000    0.296306    2.737881
75%      1.000000    3.000000    0.434531    3.465736
max      1.000000    3.000000    1.000000    6.240917

In [9]:
from sklearn.preprocessing import RobustScaler

sc = RobustScaler()
data["Age"] = sc.fit_transform(df[["Age"]])
data.describe()

         Survived      Pclass         Age        Fare
count  891.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642    0.351305    2.962246
std      0.486592    0.836071    1.015352    0.969048
min      0.000000    1.000000   -1.813846    0.000000
25%      0.000000    2.000000   -0.153846    2.187218
50%      0.000000    3.000000    0.000000    2.737881
75%      1.000000    3.000000    0.846154    3.465736
max      1.000000    3.000000    4.307692    6.240917

In [10]:
data.head()

   Survived  Pclass     Sex       Age      Fare
0         0       3    male -0.153846  2.110213
1         1       1  female  1.076923  4.280593
2         1       3  female  0.153846  2.188856
3         1       1  female  0.846154  3.990834
4         0       3    male  0.846154  2.202765

In [11]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
data["Sex"] = le.fit_transform(data["Sex"])
data["Sex"] = to_categorical(data["Sex"])
data["Pclass"] = to_categorical(data["Pclass"])

In [12]:
data.head()

   Survived  Pclass  Sex       Age      Fare
0         0     0.0  0.0 -0.153846  2.110213
1         1     0.0  1.0  1.076923  4.280593
2         1     0.0  0.0  0.153846  2.188856
3         1     0.0  1.0  0.846154  3.990834
4         0     0.0  0.0  0.846154  2.202765

In [111]:
X_train, X_test, y_train, y_test = train_test_split(data.iloc[:,1:], data.iloc[:,0], test_size=0.2, random_state=42)
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((712, 4), (712,), (179, 4), (179,))

In [112]:
from tensorflow.keras.layers import Flatten, Dense, Dropout
from tensorflow.keras import Sequential

model = Sequential()
model.add(Flatten(input_shape=(4,)))
model.add(Dense(4,activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(8,activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(1,activation='sigmoid'))
model.summary()

Model: "sequential_23"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 flatten_23 (Flatten)        (None, 4)                 0

 dense_72 (Dense)            (None, 4)                 20

 dropout_45 (Dropout)        (None, 4)                 0

 dense_73 (Dense)            (None, 8)                 40

 dropout_46 (Dropout)        (None, 8)                 0

 dense_74 (Dense)            (None, 1)                 9

=================================================================
Total params: 69 (276.00 Byte)
Trainable params: 69 (276.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [113]:
model.compile(optimizer="adam",
              loss="binary_crossentropy",
              metrics=["accuracy"])

In [114]:
history = model.fit(X_train, y_train, epochs=200)

Epoch 1/200
23/23 [==============================] - 1s 2ms/step - loss: 0.8040 - accuracy: 0.5787
Epoch 2/200
23/23 [==============================] - 0s 2ms/step - loss: 0.7622 - accuracy: 0.5702
Epoch 3/200
23/23 [==============================] - 0s 2ms/step - loss: 0.7343 - accuracy: 0.5632
Epoch 4/200
23/23 [==============================] - 0s 2ms/step - loss: 0.7161 - accuracy: 0.5843
Epoch 5/200
23/23 [==============================] - 0s 1ms/step - loss: 0.7137 - accuracy: 0.5955
Epoch 6/200
23/23 [==============================] - 0s 1ms/step - loss: 0.6959 - accuracy: 0.5829
Epoch 7/200
23/23 [==============================] - 0s 1ms/step - loss: 0.6861 - accuracy: 0.6039
Epoch 8/200
23/23 [==============================] - 0s 2ms/step - loss: 0.6750 - accuracy: 0.6292
Epoch 9/200
23/23 [==============================] - 0s 2ms/step - loss: 0.6786 - accuracy: 0.6404
Epoch 10/200
23/23 [==============================] - 0s 2ms/step - loss: 0.6692 - accuracy: 0.6306
Epoch 11/200
23/23 [==============================] - 0s 2ms/step - loss: 0.6695 - accuracy: 0.6531
Epoch 12/200
23/23 [==============================] - 0s 1ms/step - loss: 0.6623 - accuracy: 0.6587
Epoch 13/200
23/23 [==============================] - 0s 2ms/step - loss: 0.6475 - accuracy: 0.6587
Epoch 14/200
23/23 [==============================] - 0s 2ms/step - loss: 0.6345 - accuracy: 0.6671
Epoch 15/200
23/23 [==============================] - 0s 2ms/step - loss: 0.6346 - accuracy: 0.6657
Epoch 16/200
23/23 [==============================] - 0s 2ms/step - loss: 0.6366 - accuracy: 0.6756
Epoch 17/200
23/23 [==============================] - 0s 2ms/step - loss: 0.6216 - accuracy: 0.6938
Epoch 18/200
23/23 [==============================] - 0s 1ms/step - loss: 0.6131 - accuracy: 0.6840
Epoch 19/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5912 - accuracy: 0.7079
Epoch 20/200
23/23 [==============================] - 0s 2ms/step - loss: 0.6037 - accuracy: 0.6980
Epoch 21/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5868 - accuracy: 0.7191
Epoch 22/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5879 - accuracy: 0.7079
Epoch 23/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5709 - accuracy: 0.7177
Epoch 24/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5640 - accuracy: 0.7107
Epoch 25/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5648 - accuracy: 0.7135
Epoch 26/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5712 - accuracy: 0.7135
Epoch 27/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5666 - accuracy: 0.7388
Epoch 28/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5601 - accuracy: 0.7247
Epoch 29/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5555 - accuracy: 0.7388
Epoch 30/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5497 - accuracy: 0.7289
Epoch 31/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5466 - accuracy: 0.7388
Epoch 32/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5602 - accuracy: 0.7360
Epoch 33/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5518 - accuracy: 0.7261
Epoch 34/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5380 - accuracy: 0.7331
Epoch 35/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5468 - accuracy: 0.7514
Epoch 36/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5465 - accuracy: 0.7388
Epoch 37/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5303 - accuracy: 0.7612
Epoch 38/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5618 - accuracy: 0.7191
Epoch 39/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5540 - accuracy: 0.7374
Epoch 40/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5347 - accuracy: 0.7570
Epoch 41/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5285 - accuracy: 0.7486
Epoch 42/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5399 - accuracy: 0.7331
Epoch 43/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5413 - accuracy: 0.7458
Epoch 44/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5369 - accuracy: 0.7444
Epoch 45/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5504 - accuracy: 0.7388
Epoch 46/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5454 - accuracy: 0.7317
Epoch 47/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5436 - accuracy: 0.7514
Epoch 48/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5414 - accuracy: 0.7458
Epoch 49/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5239 - accuracy: 0.7528
Epoch 50/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5224 - accuracy: 0.7598
Epoch 51/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5433 - accuracy: 0.7331
Epoch 52/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5302 - accuracy: 0.7430
Epoch 53/200
23/23 [==============================] - 0s 3ms/step - loss: 0.5429 - accuracy: 0.7346
Epoch 54/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5482 - accuracy: 0.7360
Epoch 55/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5300 - accuracy: 0.7416
Epoch 56/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5342 - accuracy: 0.7598
Epoch 57/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5490 - accuracy: 0.7303
Epoch 58/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5411 - accuracy: 0.7247
Epoch 59/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5474 - accuracy: 0.7416
Epoch 60/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5270 - accuracy: 0.7500
Epoch 61/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5329 - accuracy: 0.7430
Epoch 62/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5431 - accuracy: 0.7472
Epoch 63/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5137 - accuracy: 0.7570
Epoch 64/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5205 - accuracy: 0.7598
Epoch 65/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5374 - accuracy: 0.7556
Epoch 66/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5195 - accuracy: 0.7458
Epoch 67/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5377 - accuracy: 0.7472
Epoch 68/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5394 - accuracy: 0.7374
Epoch 69/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5414 - accuracy: 0.7374
Epoch 70/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5359 - accuracy: 0.7402
Epoch 71/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5317 - accuracy: 0.7528
Epoch 72/200
23/23 [==============================] - 0s 3ms/step - loss: 0.5211 - accuracy: 0.7612
Epoch 73/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5370 - accuracy: 0.7542
Epoch 74/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5354 - accuracy: 0.7458
Epoch 75/200
23/23 [==============================] - 0s 845us/step - loss: 0.5136 - accuracy: 0.7711
Epoch 76/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5292 - accuracy: 0.7472
Epoch 77/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5357 - accuracy: 0.7472
Epoch 78/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5262 - accuracy: 0.7388
Epoch 79/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5233 - accuracy: 0.7472
Epoch 80/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5211 - accuracy: 0.7584
Epoch 81/200
23/23 [==============================] - 0s 3ms/step - loss: 0.5181 - accuracy: 0.7612
Epoch 82/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5493 - accuracy: 0.7360
Epoch 83/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5344 - accuracy: 0.7374
Epoch 84/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5310 - accuracy: 0.7346
Epoch 85/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5290 - accuracy: 0.7444
Epoch 86/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5509 - accuracy: 0.7374
Epoch 87/200
23/23 [==============================] - 0s 3ms/step - loss: 0.5274 - accuracy: 0.7486
Epoch 88/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5316 - accuracy: 0.7626
Epoch 89/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5280 - accuracy: 0.7416
Epoch 90/200
23/23 [==============================] - 0s 3ms/step - loss: 0.5479 - accuracy: 0.7346
Epoch 91/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5254 - accuracy: 0.7500
Epoch 92/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5299 - accuracy: 0.7402
Epoch 93/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5355 - accuracy: 0.7500
Epoch 94/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5398 - accuracy: 0.7472
Epoch 95/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5269 - accuracy: 0.7654
Epoch 96/200
23/23 [==============================] - 0s 912us/step - loss: 0.5207 - accuracy: 0.7514
Epoch 97/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5301 - accuracy: 0.7514
Epoch 98/200
23/23 [==============================] - 0s 3ms/step - loss: 0.5381 - accuracy: 0.7430
Epoch 99/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5338 - accuracy: 0.7444
Epoch 100/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5301 - accuracy: 0.7430
Epoch 101/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5121 - accuracy: 0.7795
Epoch 102/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5310 - accuracy: 0.7598
Epoch 103/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5143 - accuracy: 0.7542
Epoch 104/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5293 - accuracy: 0.7430
Epoch 105/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5099 - accuracy: 0.7598
Epoch 106/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5197 - accuracy: 0.7500
Epoch 107/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5290 - accuracy: 0.7654
Epoch 108/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5098 - accuracy: 0.7753
Epoch 109/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5223 - accuracy: 0.7416
Epoch 110/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5315 - accuracy: 0.7331
Epoch 111/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5262 - accuracy: 0.7416
Epoch 112/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5215 - accuracy: 0.7556
Epoch 113/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5212 - accuracy: 0.7346
Epoch 114/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5209 - accuracy: 0.7528
Epoch 115/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5205 - accuracy: 0.7430
Epoch 116/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5201 - accuracy: 0.7598
Epoch 117/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5178 - accuracy: 0.7556
Epoch 118/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5031 - accuracy: 0.7654
Epoch 119/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5099 - accuracy: 0.7584
Epoch 120/200
23/23 [==============================] - 0s 3ms/step - loss: 0.5255 - accuracy: 0.7528
Epoch 121/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5297 - accuracy: 0.7458
Epoch 122/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5216 - accuracy: 0.7458
Epoch 123/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5185 - accuracy: 0.7472
Epoch 124/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5159 - accuracy: 0.7500
Epoch 125/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5279 - accuracy: 0.7556
Epoch 126/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5154 - accuracy: 0.7542
Epoch 127/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5051 - accuracy: 0.7683
Epoch 128/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5154 - accuracy: 0.7430
Epoch 129/200
23/23 [==============================] - 0s 1ms/step - loss: 0.4978 - accuracy: 0.7612
Epoch 130/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5153 - accuracy: 0.7528
Epoch 131/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5175 - accuracy: 0.7612
Epoch 132/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5074 - accuracy: 0.7570
Epoch 133/200
23/23 [==============================] - 0s 3ms/step - loss: 0.5124 - accuracy: 0.7542
Epoch 134/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5174 - accuracy: 0.7556
Epoch 135/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5297 - accuracy: 0.7542
Epoch 136/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5313 - accuracy: 0.7416
Epoch 137/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5230 - accuracy: 0.7472
Epoch 138/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5216 - accuracy: 0.7303
Epoch 139/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5199 - accuracy: 0.7570
Epoch 140/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5215 - accuracy: 0.7669
Epoch 141/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5279 - accuracy: 0.7388
Epoch 142/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5255 - accuracy: 0.7598
Epoch 143/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5203 - accuracy: 0.7500
Epoch 144/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5297 - accuracy: 0.7416
Epoch 145/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5224 - accuracy: 0.7486
Epoch 146/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5272 - accuracy: 0.7486
Epoch 147/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5137 - accuracy: 0.7514
Epoch 148/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5157 - accuracy: 0.7598
Epoch 149/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5227 - accuracy: 0.7514
Epoch 150/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5282 - accuracy: 0.7472
Epoch 151/200
23/23 [==============================] - 0s 833us/step - loss: 0.5178 - accuracy: 0.7458
Epoch 152/200
23/23 [==============================] - 0s 3ms/step - loss: 0.5026 - accuracy: 0.7683
Epoch 153/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5168 - accuracy: 0.7528
Epoch 154/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5091 - accuracy: 0.7795
Epoch 155/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5177 - accuracy: 0.7626
Epoch 156/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5046 - accuracy: 0.7584
Epoch 157/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5139 - accuracy: 0.7640
Epoch 158/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5066 - accuracy: 0.7654
Epoch 159/200
23/23 [==============================] - 0s 2ms/step - loss: 0.4976 - accuracy: 0.7809
Epoch 160/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5177 - accuracy: 0.7570
Epoch 161/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5222 - accuracy: 0.7528
Epoch 162/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5179 - accuracy: 0.7612
Epoch 163/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5143 - accuracy: 0.7514
Epoch 164/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5072 - accuracy: 0.7598
Epoch 165/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5198 - accuracy: 0.7584
Epoch 166/200
23/23 [==============================] - 0s 3ms/step - loss: 0.5126 - accuracy: 0.7753
Epoch 167/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5166 - accuracy: 0.7444
Epoch 168/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5185 - accuracy: 0.7500
Epoch 169/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5028 - accuracy: 0.7669
Epoch 170/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5136 - accuracy: 0.7584
Epoch 171/200
23/23 [==============================] - 0s 2ms/step - loss: 0.4965 - accuracy: 0.7837
Epoch 172/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5163 - accuracy: 0.7556
Epoch 173/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5165 - accuracy: 0.7626
Epoch 174/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5064 - accuracy: 0.7584
Epoch 175/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5093 - accuracy: 0.7584
Epoch 176/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5133 - accuracy: 0.7669
Epoch 177/200
23/23 [==============================] - 0s 3ms/step - loss: 0.5106 - accuracy: 0.7781
Epoch 178/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5068 - accuracy: 0.7640
Epoch 179/200
23/23 [==============================] - 0s 2ms/step - loss: 0.4987 - accuracy: 0.7683
Epoch 180/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5209 - accuracy: 0.7500
Epoch 181/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5107 - accuracy: 0.7669
Epoch 182/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5045 - accuracy: 0.7584
Epoch 183/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5115 - accuracy: 0.7570
Epoch 184/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5267 - accuracy: 0.7458
Epoch 185/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5226 - accuracy: 0.7472
Epoch 186/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5067 - accuracy: 0.7669
Epoch 187/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5152 - accuracy: 0.7556
Epoch 188/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5111 - accuracy: 0.7556
Epoch 189/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5034 - accuracy: 0.7626
Epoch 190/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5180 - accuracy: 0.7486
Epoch 191/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5071 - accuracy: 0.7654
Epoch 192/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5187 - accuracy: 0.7626
Epoch 193/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5123 - accuracy: 0.7528
Epoch 194/200
23/23 [==============================] - 0s 2ms/step - loss: 0.4873 - accuracy: 0.7851
Epoch 195/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5098 - accuracy: 0.7683
Epoch 196/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5001 - accuracy: 0.7795
Epoch 197/200
23/23 [==============================] - 0s 2ms/step - loss: 0.5054 - accuracy: 0.7851
Epoch 198/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5215 - accuracy: 0.7669
Epoch 199/200
23/23 [==============================] - 0s 1ms/step - loss: 0.5212 - accuracy: 0.7753

In [115]:
test_loss, test_acc = model.evaluate(X_test, y_test, verbose=2)
print("\n테스트 정확도 :",test_acc)

6/6 - 0s - loss: 0.4974 - accuracy: 0.7877 - 112ms/epoch - 19ms/step

테스트 정확도 : 0.7877094745635986